trigger:
  batch: true
  branches:
    include:
      - migration-analytics
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - migration-analytics

stages:
  - stage: DockerHub
    displayName: Docker Hub
    jobs:
      - job: dockerhub
        displayName: Build and Push to Docker Hub
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHub'
              repository: 'carlosthe19916/insights-rbac'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile-analytics'
              tags: |
                $(Build.BuildNumber)
                latest
